### ISSUE TITLE
Certain slog.Record properties are ignored

### ISSUE THREAD

**Issue by kluzzebass** [samber/slog-datadog#2]
When converting a `slog.Record` into a Datadog log message, certain important properties are not included, such as `Message`, `Level`, etc. 

I'm not sure where the missing code is supposed to go, but a candidate might be somewhere here: https://github.com/samber/slog-datadog/blob/0d90483e3a0a57a79b59df64ee5d30d569a70005/converter.go#L27

As it is, all log lines show up up in Datadog with no message or level attached, but with all other custom attributes attached.

**Comment by kluzzebass** [comment]
I looked at the corresponding code in your slog-logstash handler, and it seems to be an easy fix: https://github.com/samber/slog-logstash/blob/2496cab3a2adde61b5fa22e29192f4de55234a1e/converter.go#L26

**Comment by samber** [comment]
What the f*** (!)

I don't know what happened here. Thanks for the report. I just made a fix.

-> v2.2.1
